### ISSUE TITLE
Since v1.12.1 axios issue is beign thrown 

### ISSUE THREAD

**Issue by ronanbrowne** [snyk-tech-services/snyk-delta#190]
Since the last release, `v1.12.1`, the following issue has been observed in our pipelines.

```
[2024-10-10T10:56:04.841Z] + + snyk-linux test --configuration-matching=^((?!test).)*$ --file=platform-test/build.gradle --policy-path=.snyk --severity-threshold=high --json
[2024-10-10T10:56:04.841Z] snyk-delta -d --baselineOrg **** --baselineProject 558f9049-57ff-48f2-aff9-0caf7c0e17d5
[2024-10-10T10:56:04.841Z] Error: Cannot find module '/snapshot/project/node_modules/snyk-request-manager/node_modules/axios/dist/node/axios.cjs'
[2024-10-10T10:56:04.842Z] 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
[2024-10-10T10:56:04.842Z]     at createEsmNotFoundErr (internal/modules/cjs/loader.js:842:15)
[2024-10-10T10:56:04.842Z]     at finalizeEsmResolution (internal/modules/cjs/loader.js:835:15)
[2024-10-10T10:56:04.842Z]     at resolveExports (internal/modules/cjs/loader.js:424:14)
[2024-10-10T10:56:04.842Z]     at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
[2024-10-10T10:56:04.842Z]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
[2024-10-10T10:56:04.842Z]     at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
[2024-10-10T10:56:04.842Z]     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
[2024-10-10T10:56:04.842Z]     at Module.require (internal/modules/cjs/loader.js:887:19)
[2024-10-10T10:56:04.842Z]     at Module.require (pkg/prelude/bootstrap.js:1851:31)
[2024-10-10T10:56:04.842Z]     at require (internal/modules/cjs/helpers.js:74:18)
script returned exit code 1
```

I can see from the [change log](https://github.com/snyk-tech-services/snyk-delta/releases/tag/v1.12.1) that `Axios` has been updated. Can this please be investigated?

**Comment by ronanbrowne** [comment]
FYI @aarlaud any advice on this

**Comment by aarlaud** [comment]
What's your node version?

**Comment by ronanbrowne** [comment]
> What's your node version?

`v18.20.4`

**Comment by aarlaud** [comment]
are you using the binary?

**Comment by ronanbrowne** [comment]
> are you using the binary?

Yes, for additional context, this tool executes in a docker image, the building of the image installs the binary grabbing it form the GH release page via a curl (getting the lastest version for the specified architecture)

**Comment by aarlaud** [comment]
problem is with the binary indeed. investigating

**Comment by ronanbrowne** [comment]
Much appreciated @aarlaud - I'll confirm this tomorrow and loop back
